// Generated by https://quicktype.io

export interface Entry {
  _id: string;
  itemName: string;
  calorieAmount: number;
  timestamp: string;
  userId?: string;
  user?: User;
  __v: number;
}

export interface User {
  _id: string;
  name: string;
  email: string;
}

// Generated by https://quicktype.io

export interface Report {
  calorieAmountReport: CalorieAmountReport[];
  entryAddedMetrics: EntryAddedMetrics;
  avgCalAddedPerUser: number;
}

export interface CalorieAmountReport {
  _id: string;
  avgCalories: number;
  userDetails: UserDetails;
}

export interface UserDetails {
  _id: string;
  name: string;
  email: string;
  role: string;
  __v: number;
}

export interface EntryAddedMetrics {
  secondWeek: Week;
  firstWeek: Week;
}

export interface Week {
  _id: string;
  count: number;
}


// Generated by https://quicktype.io

export interface UserInfo {
  id: string;
  email: string;
  role: string;
  iat: number;
  exp: number;
}

export interface MetaInfo {

}


// Generated by https://quicktype.io

export interface UserList {
  _id: string;
  name: string;
  email: string;
}
